---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.project }}-{{ .Values.kind }}-{{ .Values.app_env }}
  labels:
    project: {{ .Values.project }}
    kind: {{ .Values.kind }}
    app_env: {{ .Values.app_env }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.deployment.maxSurge }}
      maxUnavailable: 0
  selector:
    matchLabels:
      project: {{ .Values.project }}
      kind: {{ .Values.kind }}
      app_env: {{ .Values.app_env }}
  template:
    metadata:
      labels:
        project: {{ .Values.project }}
        kind: {{ .Values.kind }}
        app_env: {{ .Values.app_env }}
    spec:
      containers:
      - name: {{ .Values.project }}-{{ .Values.kind }}-{{ .Values.app_env }}
        image: {{ include "container-image" . }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: {{ .Values.deployment.app_port }}
        resources:
          requests: 
            memory: "1G"
            cpu: "500m"
          limits:
            memory: "2G"
        startupProbe:
          httpGet:
            path: {{ .Values.deployment.probe_path }}
            port: {{ .Values.deployment.app_port }}
          initialDelaySeconds: 10
          failureThreshold: 20
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.probe_path }}
            port: {{ .Values.deployment.app_port }}
          failureThreshold: 3
          periodSeconds: 30
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - {{ .Values.affinity.role }}
              - key: environment
                operator: In
                values:
                - {{ .Values.affinity.environment }}
