---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.project }}-{{ .Values.kind }}-{{ .Values.app_env }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.project }}-{{ .Values.kind }}-{{ .Values.app_env }}
  minReplicas: {{ .Values.podautoscaler.minReplicas }}
  maxReplicas: {{ .Values.podautoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
