---
project: ''   # project name on git
kind: ''      # subgroup on git
app_env: ''   # branch on git
namespace: '' # namespase on k8s

deployment:
  replicas: 1
  container:
    image: ''
  maxSurge: 1
  app_port: '80'
  probe_path: '/'

host_url: ''

affinity:
  role: ''
  environment: ''

podautoscaler:
  minReplicas: 1
  maxReplicas: 3
